# filename: Gemfile
source 'https://rubygems.org'

gem 'dotenv-rails', groups: [:development, :test]
gem 'rspec', '~>3.8.0'
gem 'selenium-webdriver', '~>4.0.0.alpha.2'
gem 'rake', '~>12.3.2'
gem 'cucumber'
gem 'watir'
gem 'webdrivers'
gem 'faker'
gem 'nokogiri'
gem 'report_builder'
gem 'parallel_tests', group: [:development, :test]
