# filename: Gemfile
source 'https://rubygems.org'

gem 'dotenv-rails', groups: [:development, :test]
gem 'rspec', '~>3.8.0'
gem 'selenium-webdriver', '~>4.0.0.alpha.2'
gem 'parallel_tests', '~>2.29.1'