name: 'sauce-action@v1'
description: 'set up and run actions'

runs:
  using: "composite"
  steps:
    - name: create config
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/scripts/
        cp config_template.yml config.yml
        echo "api-key: ${{ env.SAUCE_ACCESS_KEY }}" >> config.yml
        echo "user: ${{ env.SAUCE_USERNAME }}" >> config.yml
        echo "tunnel-identifier: ${{ env.SAUCE_TUNNEL }}" >> config.yml
        echo "auth: ['${{ env.HOST_URL }}:80:${{ env.BASIC_AUTH}}']" >> config.yml
    - name: start sauce connect
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/scripts/
        bin/sauceconnect_linux -c config.yml &
    - name: Sleep for 30s to wait for Sauce Connect ready
      shell: bash
      run: |
        echo "waiting for 30 seconds..."
        sleep 30s
        echo "//TODO: figure out how to do this by pinging SC"